name: Build and deploy ASP.Net Core app to a Windows Server

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: label

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build with dotnet
        run: dotnet build --configuration Release

      - name: Publish with dotnet
        run: dotnet publish -c Release -o ./publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v2
        with:
          name: dotnet-app-${{ github.run_number }}
          path: ./publish

  deploy:
    runs-on: label
    needs: build
    environment:
      name: 'dev'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: dotnet-app-${{ github.run_number }}
          path: ./published

      - name: copy file via ssh password
        uses: appleboy/scp-action@v0.1.4
        with:
         host: ${{ secrets.IP }}
         username: ${{ secrets.USER_NAME }}
         password: ${{ secrets.USER_PASSWORD }}
         source: "./published/*"
         target: C:\inetpub\wwwroot
