name: CD

on:
  workflow_run:
    workflows: ["CI build"]
    types:
      - completed
permissions:
  contents: read

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Stop and remove a container
        run: |
          docker stop asp.net
          docker rm -f asp.net
          
      - name: Create a container
        run: |
          docker run -itd --name asp.net my-docker-image
