name: Build and deploy ASP.Net Core app to a Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: label
    steps:
     - name: copy files to another
       run: |-
        XCOPY /i /E /s /y /c D:\POC\actions-runner\_work\aspnet-core-github-workflow-demo\aspnet-core-github-workflow-demo\publish C:\inetpub\wwwroot
