name: Build and deploy ASP.Net Core app to a Windows Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: label
    steps:
      - name: Copy folder content recursively to remote
        uses: garygrossgarten/github-action-scp@release
        with:
          local: D:\POC\actions-runner\_work\aspnet-core-github-workflow-demo\aspnet-core-github-workflow-demo\published\
          remote: C:\inetpub\wwwroot
          host: ${{ secrets.IP }}
          username: ${{ secrets.USER_NAME }}
          password: ${{ secrets.USER_PASSWORD }}
